const videoActionTypes = {
  START_REQUEST_NEWS: 'START_REQUEST_NEWS',
  SUCCESS_REQUEST_NEWS: 'SUCCESS_REQUEST_NEWS',
  FAILURE_REQUEST_NEWS: 'FAILURE_REQUEST_NEWS',
  GET_VIDEO: 'GET_VIDEO',

  START_REQUEST_KNOWLEDGE: 'START_REQUEST_KNOWLEDGE',
  SUCCESS_REQUEST_KNOWLEDGE: 'SUCCESS_REQUEST_KNOWLEDGE',
  FAILURE_REQUEST_KNOWLEDGE: 'FAILURE_REQUEST_KNOWLEDGE',
  GET_KNOWLEDGE_VIDEO: 'GET_NEWS_VIDEO',

  START_REQUEST_ENTERTAIN: 'START_REQUEST_ENTERTAIN',
  SUCCESS_REQUEST_ENTERTAIN: 'SUCCESS_REQUEST_ENTERTAIN',
  FAILURE_REQUEST_ENTERTAIN: 'FAILURE_REQUEST_ENTERTAIN',
  GET_ENTERTAIN_VIDEO: 'GET_ENTERTAIN_VIDEO',
};

export default videoActionTypes;
